services:
  postgres:
    image: 'postgres:latest'
    container_name: chatbot_postgres
    restart: always
    environment:
      - 'POSTGRES_DB=chatbotdb'
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
